site_name: Shvayambhu LLM Documentation
site_url: https://shvayambhu.ai
site_author: Shvayambhu Team
site_description: >-
  Documentation for Shvayambhu, the world's first self-evolving,
  completely offline Large Language Model

repo_name: shvayambhu/shvayambhu
repo_url: https://github.com/shvayambhu/shvayambhu
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shvayambhu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shvayambhu
    - icon: fontawesome/brands/discord
      link: https://discord.gg/shvayambhu

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: shvayambhu
      repo: shvayambhu
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Examples: getting-started/examples.md
  - Architecture:
    - Overview: architecture/overview.md
    - BLT (Byte Latent Transformer): architecture/blt.md
    - SEAL (Self-Adapting): architecture/seal.md
    - ProRL (Reasoning): architecture/prorl.md
    - Safety Systems: architecture/safety.md
  - User Guide:
    - Basic Usage: guide/basic-usage.md
    - Advanced Features: guide/advanced.md
    - Performance Tuning: guide/performance.md
    - Troubleshooting: guide/troubleshooting.md
  - Developer Guide:
    - Contributing: developer/contributing.md
    - Coding Standards: developer/coding-standards.md
    - API Reference: developer/api-reference.md
    - Building from Source: developer/building.md
  - Training:
    - Overview: training/overview.md
    - Bootstrap Training: training/bootstrap.md
    - Synthetic Data: training/synthetic.md
    - Active Learning: training/active-learning.md
  - Benchmarks:
    - Performance: benchmarks/performance.md
    - Quality: benchmarks/quality.md
    - Comparisons: benchmarks/comparisons.md
  - FAQ: faq.md
  - Changelog: changelog.md